/**
 * @brief Common data type
 */

#include "CommonDataType.h"

MAP_ENUM_STR(LABEL_INDICATOR, DEF_LABEL_INDICATOR)
MAP_ENUM_STR(BATTERY_TYPE, DEF_BATTERY_TYPE)
MAP_ENUM_STR(COMPORT_TYPE, DEF_COMPORT_TYPE)
MAP_ENUM_STR(MODULE_NAME, DEF_MODULE_NAME)

#ifdef _WIN64
MAP_ENUM_WSTR(MODULE_NAME, DEF_MODULE_NAME)
#endif

MAP_ENUM_STR(COLOR_TYPE, DEF_COLOR_TYPE)

std::unordered_map<COLOR_TYPE, uint32_t> mapColor =
{
    { COLOR_TYPE::DEFAULT_COLOR, 0xFFFFFF },
    { COLOR_TYPE::RED, 0xFF0000 },
    { COLOR_TYPE::GREEN, 0x00FF00 },
};
