/**
 * @brief Common data type
 */

#include "CommonDataType.h"

MAP_ENUM_STR(LABEL_INDICATOR, DEF_LABEL_INDICATOR)
MAP_ENUM_STR(BATTERY_TYPE, DEF_BATTERY_TYPE)
MAP_ENUM_STR(COMPORT_TYPE, DEF_COMPORT_TYPE)
MAP_ENUM_STR(MODULE_NAME, DEF_MODULE_NAME)

#ifdef _WIN64
MAP_ENUM_WSTR(MODULE_NAME, DEF_MODULE_NAME)
#endif

std::unordered_map<TEXT_LABEL, std::string> map_TextLabel = {
    { TEXT_LABEL::E_READY     , "READY"   },
    { TEXT_LABEL::E_FIRST     , "FIRST"   },
    { TEXT_LABEL::E_NO        , "NO"      },
    { TEXT_LABEL::E_BLANK     , "BLANK"   },
    { TEXT_LABEL::E_NOTHING   , "NOTHING" },
    { TEXT_LABEL::E_YES       , "YES"     },
    { TEXT_LABEL::E_WHAT      , "WHAT"    },
    { TEXT_LABEL::E_UHHH      , "UHHH"    },
    { TEXT_LABEL::E_LEFT      , "LEFT"    },
    { TEXT_LABEL::E_RIGHT     , "RIGHT"   },
    { TEXT_LABEL::E_MIDDLE    , "MIDDLE"  },
    { TEXT_LABEL::E_OKAY      , "OKAY"    },
    { TEXT_LABEL::E_WAIT      , "WAIT"    },
    { TEXT_LABEL::E_PRESS     , "PRESS"   },
    { TEXT_LABEL::E_YOU       , "YOU"     },
    { TEXT_LABEL::E_YOU_ARE   , "YOU ARE" },
    { TEXT_LABEL::E_YOUR      , "YOUR"    },
    { TEXT_LABEL::E_YOURE     , "YOU'RE"  },
    { TEXT_LABEL::E_UR        , "UR"      },
    { TEXT_LABEL::E_U         , "U"       },
    { TEXT_LABEL::E_UH_HUH    , "UH HUH"  },
    { TEXT_LABEL::E_UH_UH     , "UH UH"   },
    { TEXT_LABEL::E_WHAT_QMARK, "WHAT?"   },
    { TEXT_LABEL::E_DONE      , "DONE"    },
    { TEXT_LABEL::E_NEXT      , "NEXT"    },
    { TEXT_LABEL::E_HOLD      , "HOLD"    },
    { TEXT_LABEL::E_SURE      , "SURE"    },
    { TEXT_LABEL::E_LIKE      , "LIKE"    },
};

std::unordered_map<TEXT_DISPLAY, std::tuple<std::string, uint8_t>> map_TextDisplayWithFocusPostion = {
    { TEXT_DISPLAY::E_YES     , { "YES"     , 3 } },
    { TEXT_DISPLAY::E_FIRST   , { "FIRST"   , 2 } },
    { TEXT_DISPLAY::E_DISPLAY , { "DISPLAY" , 6 } },
    { TEXT_DISPLAY::E_OKAY    , { "OKAY"    , 2 } },
    { TEXT_DISPLAY::E_SAYS    , { "SAYS"    , 6 } },
    { TEXT_DISPLAY::E_NOTHING , { "NOTHING" , 3 } },
    { TEXT_DISPLAY::E_EMPTY   , { ""        , 5 } },
    { TEXT_DISPLAY::E_BLANK   , { "BLANK"   , 4 } },
    { TEXT_DISPLAY::E_NO      , { "NO"      , 6 } },
    { TEXT_DISPLAY::E_LED     , { "LED"     , 3 } },
    { TEXT_DISPLAY::E_LEAD    , { "LEAD"    , 6 } },
    { TEXT_DISPLAY::E_READ    , { "READ"    , 4 } },
    { TEXT_DISPLAY::E_RED     , { "RED"     , 4 } },
    { TEXT_DISPLAY::E_REED    , { "REED"    , 5 } },
    { TEXT_DISPLAY::E_LEED    , { "LEED"    , 5 } },
    { TEXT_DISPLAY::E_HOLD_ON , { "HOLD ON" , 6 } },
    { TEXT_DISPLAY::E_YOU     , { "YOU"     , 4 } },
    { TEXT_DISPLAY::E_YOU_ARE , { "YOU ARE" , 6 } },
    { TEXT_DISPLAY::E_YOUR    , { "YOUR"    , 4 } },
    { TEXT_DISPLAY::E_YOURE   , { "YOU'RE"  , 4 } },
    { TEXT_DISPLAY::E_UR      , { "UR"      , 1 } },
    { TEXT_DISPLAY::E_THERE   , { "THERE"   , 6 } },
    { TEXT_DISPLAY::E_THEYRE  , { "THEY'RE" , 5 } },
    { TEXT_DISPLAY::E_THEIR   , { "THEIR"   , 4 } },
    { TEXT_DISPLAY::E_THEY_ARE, { "THEY ARE", 3 } },
    { TEXT_DISPLAY::E_SEE     , { "SEE"     , 6 } },
    { TEXT_DISPLAY::E_C       , { "C"       , 2 } },
    { TEXT_DISPLAY::E_CEE     , { "CEE"     , 6 } },
};

/* Display map
   Refer [On the Subject of Who’s on First] */
std::unordered_map<TEXT_LABEL, std::vector<TEXT_LABEL>> map_TextLabelList = {
    {
        TEXT_LABEL::E_READY,
        {
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_WAIT,
        }
    },
    {
        TEXT_LABEL::E_FIRST,
        {
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_FIRST,
        }
    },
    {
        TEXT_LABEL::E_NO,
        {
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_MIDDLE,
        }
    },
    {
        TEXT_LABEL::E_BLANK,
        {
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_FIRST,
        }
    },
    {
        TEXT_LABEL::E_NOTHING,
        {
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_READY,
        }
    },
    {
        TEXT_LABEL::E_YES,
        {
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_WAIT,
        }
    },
    {
        TEXT_LABEL::E_WHAT,
        {
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_RIGHT,
        }
    },
    {
        TEXT_LABEL::E_UHHH,
        {
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_FIRST,
        }
    },
    {
        TEXT_LABEL::E_LEFT,
        {
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_NOTHING,
        }
    },
    {
        TEXT_LABEL::E_RIGHT,
        {
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_FIRST,
        }
    },
    {
        TEXT_LABEL::E_MIDDLE,
        {
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_YES,
        }
    },
    {
        TEXT_LABEL::E_OKAY,
        {
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_RIGHT,
        }
    },
    {
        TEXT_LABEL::E_WAIT,
        {
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_WAIT,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_MIDDLE,
        }
    },
    {
        TEXT_LABEL::E_PRESS,
        {
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_WAIT,
        }
    },
    {
        TEXT_LABEL::E_YOU,
        {
            TEXT_LABEL::E_RIGHT,
            TEXT_LABEL::E_MIDDLE,
            TEXT_LABEL::E_YES,
            TEXT_LABEL::E_READY,
            TEXT_LABEL::E_PRESS,
            TEXT_LABEL::E_OKAY,
            TEXT_LABEL::E_NOTHING,
            TEXT_LABEL::E_UHHH,
            TEXT_LABEL::E_BLANK,
            TEXT_LABEL::E_LEFT,
            TEXT_LABEL::E_FIRST,
            TEXT_LABEL::E_WHAT,
            TEXT_LABEL::E_NO,
            TEXT_LABEL::E_WAIT,
        }
    },
    {
        TEXT_LABEL::E_YOU_ARE,
        {
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_YOU_ARE,
        }
    },
    {
        TEXT_LABEL::E_YOUR,
        {
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_DONE,
        }
    },
    {
        TEXT_LABEL::E_YOURE,
        {
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_HOLD,
        }
    },
    {
        TEXT_LABEL::E_UR,
        {
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_YOU,
        }
    },
    {
        TEXT_LABEL::E_U,
        {
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_YOUR,
        }
    },
    {
        TEXT_LABEL::E_UH_HUH,
        {
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_WHAT_QMARK,
        }
    },
    {
        TEXT_LABEL::E_UH_UH,
        {
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_WHAT_QMARK,
        }
    },
    {
        TEXT_LABEL::E_WHAT_QMARK,
        {
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_SURE,
        }
    },
    {
        TEXT_LABEL::E_DONE,
        {
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_DONE,
        }
    },
    {
        TEXT_LABEL::E_NEXT,
        {
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_YOU,
        }
    },
    {
        TEXT_LABEL::E_HOLD,
        {
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_LIKE,
        }
    },
    {
        TEXT_LABEL::E_SURE,
        {
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_YOUR,
            TEXT_LABEL::E_UH_UH,
        }
    },
    {
        TEXT_LABEL::E_LIKE,
        {
            TEXT_LABEL::E_YOURE,
            TEXT_LABEL::E_NEXT,
            TEXT_LABEL::E_U,
            TEXT_LABEL::E_UR,
            TEXT_LABEL::E_HOLD,
            TEXT_LABEL::E_DONE,
            TEXT_LABEL::E_UH_UH,
            TEXT_LABEL::E_WHAT_QMARK,
            TEXT_LABEL::E_UH_HUH,
            TEXT_LABEL::E_YOU,
            TEXT_LABEL::E_LIKE,
            TEXT_LABEL::E_SURE,
            TEXT_LABEL::E_YOU_ARE,
            TEXT_LABEL::E_YOUR,
        }
    },
};
