// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OnSliderChange(lv_event_t * e);
void OnButtonNormalClick(lv_event_t * e);
void OnArcChange(lv_event_t * e);
void OnCheckboxClick(lv_event_t * e);
void OnDropdownChange(lv_event_t * e);
void OnSwitchClick(lv_event_t * e);
void OnRollerChange(lv_event_t * e);
void OnButtonToggleClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
