// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "CommonDataType.h"
#include "CommonData.h"
#include "CommonLibrary.h"

void AutoUpdate()
{
	String_t message = GetNotify();

	if (message == MAKE_MSG(Button2Value))
	{
		_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, NumToString(Button2Value).c_str());
	}

	if (message == MAKE_MSG(SliderValue))
	{
		_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, NumToString(SliderValue).c_str());
	}

	if (message == MAKE_MSG(ArcValue))
	{
		_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, NumToString(ArcValue).c_str());
	}

	if (message == MAKE_MSG(CheckboxValue))
	{
		_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, NumToString(CheckboxValue).c_str());
	}

	if (message == MAKE_MSG(DropdownValue))
	{
		_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, DropdownValue);
	}

	if (message == MAKE_MSG(SwitchValue))
	{
		_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, NumToString(SwitchValue).c_str());
	}

	if (message == MAKE_MSG(RollerValue))
	{
		_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, RollerValue);
	}

	if (message == MAKE_MSG(OnButtonNormalClick))
	{
		_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "Clicked");
	}

	ClearNotify();
}

void OnSliderChange(lv_event_t * e)
{
	SliderValue = lv_slider_get_value(ui_Slider1);
	SetNotify(MAKE_MSG(SliderValue));
}

void OnArcChange(lv_event_t * e)
{
	ArcValue = lv_arc_get_value(ui_Arc1);
	SetNotify(MAKE_MSG(ArcValue));
}

void OnCheckboxClick(lv_event_t * e)
{
	CheckboxValue = lv_obj_get_state(ui_Checkbox1);
	SetNotify(MAKE_MSG(CheckboxValue));
}

void OnDropdownChange(lv_event_t * e)
{
	lv_dropdown_get_selected_str(ui_Dropdown1, DropdownValue, sizeof(DropdownValue));
	SetNotify(MAKE_MSG(DropdownValue));
}

void OnSwitchClick(lv_event_t * e)
{
	SwitchValue = lv_obj_get_state(ui_Switch1);
	SetNotify(MAKE_MSG(SwitchValue));
}

void OnRollerChange(lv_event_t * e)
{
	lv_roller_get_selected_str(ui_Roller1, RollerValue, sizeof(RollerValue));
	SetNotify(MAKE_MSG(RollerValue));
}

void OnButtonNormalClick(lv_event_t * e)
{
	SetNotify("MAKE_MSG(OnButtonNormalClick)");
}

void OnButtonToggleClick(lv_event_t* e)
{
	Button2Value = lv_obj_get_state(ui_Button2);
	SetNotify("MAKE_MSG(Button2Value)");
}
