// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Login
void ui_Login_screen_init(void);
lv_obj_t * ui_Login;
lv_obj_t * ui_Label4;
void ui_event_TextArea(lv_event_t * e);
lv_obj_t * ui_TextArea;
lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_lblStrike;
void ui_event_btnPlay(lv_event_t * e);
lv_obj_t * ui_btnPlay;
void ui_event_btnSetting(lv_event_t * e);
lv_obj_t * ui_btnSetting;
void ui_event_btnTimerSetting(lv_event_t * e);
lv_obj_t * ui_btnTimerSetting;
void ui_event_btnEventNote(lv_event_t * e);
lv_obj_t * ui_btnEventNote;
void ui_event_btnRestart(lv_event_t * e);
lv_obj_t * ui_btnRestart;
lv_obj_t * ui_lblTimer;
lv_obj_t * ui_imgResult;
void ui_event_sldBrightness(lv_event_t * e);
lv_obj_t * ui_sldBrightness;
// CUSTOM VARIABLES


// SCREEN: ui_Setting
void ui_Setting_screen_init(void);
lv_obj_t * ui_Setting;
lv_obj_t * ui_Label6;
lv_obj_t * ui_btnSettingModule1;
lv_obj_t * ui_btnSettingModule2;
lv_obj_t * ui_btnSettingModule3;
lv_obj_t * ui_btnSettingModule4;
lv_obj_t * ui_btnSettingModule5;
lv_obj_t * ui_btnSettingModule6;
lv_obj_t * ui_btnSettingModule7;
lv_obj_t * ui_btnSettingModule8;
lv_obj_t * ui_btnSettingModule9;
lv_obj_t * ui_btnSettingModule10;
lv_obj_t * ui_btnSettingModule11;
lv_obj_t * ui_Label3;
lv_obj_t * ui_btnSettingNeedyModule1;
lv_obj_t * ui_btnSettingNeedyModule2;
lv_obj_t * ui_btnSettingNeedyModule3;
void ui_event_btnBack(lv_event_t * e);
lv_obj_t * ui_btnBack;
// CUSTOM VARIABLES


// SCREEN: ui_TimerSetting
void ui_TimerSetting_screen_init(void);
void ui_event_TimerSetting(lv_event_t * e);
lv_obj_t * ui_TimerSetting;
void ui_event_rlSettingMinute(lv_event_t * e);
lv_obj_t * ui_rlSettingMinute;
lv_obj_t * ui_Label2;
void ui_event_rlSettingSecond(lv_event_t * e);
lv_obj_t * ui_rlSettingSecond;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label5;
void ui_event_btnTimerSettingSave(lv_event_t * e);
lv_obj_t * ui_btnTimerSettingSave;
lv_obj_t * ui_Label10;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES


// SCREEN: ui_Score
void ui_Score_screen_init(void);
void ui_event_Score(lv_event_t * e);
lv_obj_t * ui_Score;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label12;
void ui_event_rlScoreOrder(lv_event_t * e);
lv_obj_t * ui_rlScoreOrder;
lv_obj_t * ui_rlScoreModuleCount;
lv_obj_t * ui_rlScoreCompletionTime;
lv_obj_t * ui_rlScoreResult;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_TextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Login_OnTextAreaEdit(e);
    }
    if(event_code == LV_EVENT_READY) {
        Login_OnTextAreaEdit(e);
    }
}

void ui_event_btnPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnPlay, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnSetting, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnTimerSetting, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnEventNote, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        Main_OnButtonPlayClick(e);
    }
}

void ui_event_btnSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Setting_screen_init);
    }
}

void ui_event_btnTimerSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TimerSetting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_TimerSetting_screen_init);
    }
}

void ui_event_btnEventNote(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Score, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Score_screen_init);
    }
}

void ui_event_btnRestart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Main_OnButtonRestartClick(e);
    }
}

void ui_event_sldBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnBrightnessChange(e);
    }
}

void ui_event_btnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Main_screen_init);
        Setting_OnButtonBackClick(e);
    }
}

void ui_event_TimerSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_state_modify(ui_btnTimerSettingSave, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_rlSettingMinute(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_btnTimerSettingSave, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_rlSettingSecond(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_btnTimerSettingSave, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_btnTimerSettingSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnTimerSettingSave, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        TimerSetting_OnButtonSaveClick(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Main_screen_init);
    }
}

void ui_event_Score(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Score_OnLoaded(e);
    }
}

void ui_event_rlScoreOrder(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Score_OnRollerOrderChange(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Login_screen_init();
    ui_Main_screen_init();
    ui_Setting_screen_init();
    ui_TimerSetting_screen_init();
    ui_Score_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Login);
}
