// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Keypads_Project

#ifndef _KEYPADS_PROJECT_UI_H
#define _KEYPADS_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Container1;
void ui_event_btnKey1(lv_event_t * e);
extern lv_obj_t * ui_btnKey1;
extern lv_obj_t * ui_imgKey1;
void ui_event_btnKey2(lv_event_t * e);
extern lv_obj_t * ui_btnKey2;
extern lv_obj_t * ui_imgKey2;
void ui_event_btnKey3(lv_event_t * e);
extern lv_obj_t * ui_btnKey3;
extern lv_obj_t * ui_imgKey3;
void ui_event_btnKey4(lv_event_t * e);
extern lv_obj_t * ui_btnKey4;
extern lv_obj_t * ui_imgKey4;
extern lv_obj_t * ui_imgResult;
void ui_event_sldBrightness(lv_event_t * e);
extern lv_obj_t * ui_sldBrightness;
extern lv_obj_t * ui_wndTransparent;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_ae_png);    // assets/ae.png
LV_IMG_DECLARE(ui_img_success_png);    // assets/success.png
LV_IMG_DECLARE(ui_img_fail_png);    // assets/fail.png
LV_IMG_DECLARE(ui_img_at_png);    // assets/at.png
LV_IMG_DECLARE(ui_img_balloon_png);    // assets/balloon.png
LV_IMG_DECLARE(ui_img_bt_png);    // assets/bt.png
LV_IMG_DECLARE(ui_img_copyright_png);    // assets/copyright.png
LV_IMG_DECLARE(ui_img_cursive_png);    // assets/cursive.png
LV_IMG_DECLARE(ui_img_doublek_png);    // assets/doublek.png
LV_IMG_DECLARE(ui_img_dragon_png);    // assets/dragon.png
LV_IMG_DECLARE(ui_img_euro_png);    // assets/euro.png
LV_IMG_DECLARE(ui_img_filledstar_png);    // assets/filledstar.png
LV_IMG_DECLARE(ui_img_hollowstar_png);    // assets/hollowstar.png
LV_IMG_DECLARE(ui_img_hookn_png);    // assets/hookn.png
LV_IMG_DECLARE(ui_img_leftc_png);    // assets/leftc.png
LV_IMG_DECLARE(ui_img_meltedthree_png);    // assets/meltedthree.png
LV_IMG_DECLARE(ui_img_nwithhat_png);    // assets/nwithhat.png
LV_IMG_DECLARE(ui_img_omega_png);    // assets/omega.png
LV_IMG_DECLARE(ui_img_paragraph_png);    // assets/paragraph.png
LV_IMG_DECLARE(ui_img_pitchfork_png);    // assets/pitchfork.png
LV_IMG_DECLARE(ui_img_pumpkin_png);    // assets/pumpkin.png
LV_IMG_DECLARE(ui_img_questionmark_png);    // assets/questionmark.png
LV_IMG_DECLARE(ui_img_rightc_png);    // assets/rightc.png
LV_IMG_DECLARE(ui_img_six_png);    // assets/six.png
LV_IMG_DECLARE(ui_img_smileyface_png);    // assets/smileyface.png
LV_IMG_DECLARE(ui_img_squidknife_png);    // assets/squidknife.png
LV_IMG_DECLARE(ui_img_squigglyn_png);    // assets/squigglyn.png
LV_IMG_DECLARE(ui_img_tracks_png);    // assets/tracks.png
LV_IMG_DECLARE(ui_img_upsidedowny_png);    // assets/upsidedowny.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
