// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef _HOST_TIMER_PROJECT_UI_H
#define _HOST_TIMER_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Login.h"
#include "ui_Main.h"
#include "ui_ModuleSelect.h"
#include "ui_TimerSelect.h"
#include "ui_Score.h"
#include "ui_Information.h"
#include "ui_Result.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_prohibit_png);    // assets/prohibit.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_leaderboard_png);    // assets/leaderboard.png
LV_IMG_DECLARE(ui_img_info_i_png);    // assets/info_i.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets/arrow_right.png
LV_IMG_DECLARE(ui_img_arrow_left_png);    // assets/arrow_left.png
LV_IMG_DECLARE(ui_img_leaderboard_45_png);    // assets/leaderboard_45.png
LV_IMG_DECLARE(ui_img_exit_png);    // assets/exit.png
LV_IMG_DECLARE(ui_img_fail_png);    // assets/fail.png
LV_IMG_DECLARE(ui_img_stamp_defused_png);    // assets/stamp_defused.png
LV_IMG_DECLARE(ui_img_stamp_exploded_png);    // assets/stamp_exploded.png
LV_IMG_DECLARE(ui_img_success_png);    // assets/success.png

// FONTS
LV_FONT_DECLARE(ui_font_Digit);
LV_FONT_DECLARE(ui_font_Digit_45);
LV_FONT_DECLARE(ui_font_XFail);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
