// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Mazes_Project

#ifndef _MAZES_PROJECT_UI_H
#define _MAZES_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Main.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_maze0_png);    // assets/maze0.png
LV_IMG_DECLARE(ui_img_assistant_navigation_png);    // assets/assistant_navigation.png
LV_IMG_DECLARE(ui_img_arrow_up_png);    // assets/arrow_up.png
LV_IMG_DECLARE(ui_img_arrow_left_png);    // assets/arrow_left.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets/arrow_right.png
LV_IMG_DECLARE(ui_img_arrow_down_png);    // assets/arrow_down.png
LV_IMG_DECLARE(ui_img_success_png);    // assets/success.png
LV_IMG_DECLARE(ui_img_fail_png);    // assets/fail.png
LV_IMG_DECLARE(ui_img_maze1_png);    // assets/maze1.png
LV_IMG_DECLARE(ui_img_maze2_png);    // assets/maze2.png
LV_IMG_DECLARE(ui_img_maze3_png);    // assets/maze3.png
LV_IMG_DECLARE(ui_img_maze4_png);    // assets/maze4.png
LV_IMG_DECLARE(ui_img_maze5_png);    // assets/maze5.png
LV_IMG_DECLARE(ui_img_maze6_png);    // assets/maze6.png
LV_IMG_DECLARE(ui_img_maze7_png);    // assets/maze7.png
LV_IMG_DECLARE(ui_img_maze8_png);    // assets/maze8.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
