// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Login_OnTextAreaEdit(lv_event_t * e);
void Main_OnLabelStrike(lv_event_t * e);
void Main_OnButtonPlayClick(lv_event_t * e);
void OnBrightnessChange(lv_event_t * e);
void ModuleSelect_OnButtonNextClick(lv_event_t * e);
void TimerSelect_OnButtonNextClick(lv_event_t * e);
void Score_OnLoaded(lv_event_t * e);
void Score_OnRollerOrderChange(lv_event_t * e);
void Score_OnClickBack(lv_event_t * e);
void Result_OnLoaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
