// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: NeedyKnobs_Project

#ifndef UI_HELPSCREEN_H
#define UI_HELPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HelpScreen
extern void ui_HelpScreen_screen_init(void);
extern void ui_HelpScreen_screen_destroy(void);
extern lv_obj_t * ui_HelpScreen;
extern void ui_event_btnBack(lv_event_t * e);
extern lv_obj_t * ui_btnBack;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_lblLed19;
extern lv_obj_t * ui_lblLed13;
extern lv_obj_t * ui_lblLed14;
extern lv_obj_t * ui_lblLed15;
extern lv_obj_t * ui_lblLed16;
extern lv_obj_t * ui_lblLed17;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_lblLed25;
extern lv_obj_t * ui_lblLed18;
extern lv_obj_t * ui_lblLed20;
extern lv_obj_t * ui_lblLed21;
extern lv_obj_t * ui_lblLed22;
extern lv_obj_t * ui_lblLed23;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_lblLed24;
extern lv_obj_t * ui_lblLed26;
extern lv_obj_t * ui_lblLed27;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_lblLed28;
extern lv_obj_t * ui_lblLed29;
extern lv_obj_t * ui_lblLed30;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_lblLed31;
extern lv_obj_t * ui_lblLed32;
extern lv_obj_t * ui_lblLed33;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_lblLed34;
extern lv_obj_t * ui_lblLed35;
extern lv_obj_t * ui_lblLed36;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

