// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: NeedyKnobs_Project

#include "ui.h"

lv_obj_t * ui_HelpScreen = NULL;
lv_obj_t * ui_btnBack = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_lblLed19 = NULL;
lv_obj_t * ui_lblLed13 = NULL;
lv_obj_t * ui_lblLed14 = NULL;
lv_obj_t * ui_lblLed15 = NULL;
lv_obj_t * ui_lblLed16 = NULL;
lv_obj_t * ui_lblLed17 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_lblLed25 = NULL;
lv_obj_t * ui_lblLed18 = NULL;
lv_obj_t * ui_lblLed20 = NULL;
lv_obj_t * ui_lblLed21 = NULL;
lv_obj_t * ui_lblLed22 = NULL;
lv_obj_t * ui_lblLed23 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_lblLed24 = NULL;
lv_obj_t * ui_lblLed26 = NULL;
lv_obj_t * ui_lblLed27 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_lblLed28 = NULL;
lv_obj_t * ui_lblLed29 = NULL;
lv_obj_t * ui_lblLed30 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_lblLed31 = NULL;
lv_obj_t * ui_lblLed32 = NULL;
lv_obj_t * ui_lblLed33 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_lblLed34 = NULL;
lv_obj_t * ui_lblLed35 = NULL;
lv_obj_t * ui_lblLed36 = NULL;
// event funtions
void ui_event_btnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_HelpScreen_screen_init(void)
{
    ui_HelpScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HelpScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_HelpScreen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_HelpScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_HelpScreen, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HelpScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HelpScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HelpScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HelpScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HelpScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_HelpScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HelpScreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBack = lv_button_create(ui_HelpScreen);
    lv_obj_set_width(ui_btnBack, 45);
    lv_obj_set_height(ui_btnBack, 45);
    lv_obj_set_x(ui_btnBack, -135);
    lv_obj_set_y(ui_btnBack, -95);
    lv_obj_set_align(ui_btnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBack, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBack, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnBack, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnBack, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_HelpScreen);
    lv_obj_set_width(ui_Label14, 70);
    lv_obj_set_height(ui_Label14, 70);
    lv_obj_set_x(ui_Label14, 68);
    lv_obj_set_y(ui_Label14, 11);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "");
    lv_obj_remove_flag(ui_Label14, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_Label14, &ui_img_rotate_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_HelpScreen);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 65);
    lv_obj_set_height(ui_Container7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container7, -39);
    lv_obj_set_y(ui_Container7, 8);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_Container7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label7, 30);
    lv_obj_set_height(ui_Label7, 30);
    lv_obj_set_x(ui_Label7, 68);
    lv_obj_set_y(ui_Label7, 12);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "1");
    lv_obj_remove_flag(ui_Label7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label5, 30);
    lv_obj_set_height(ui_Label5, 30);
    lv_obj_set_x(ui_Label5, 68);
    lv_obj_set_y(ui_Label5, 11);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "");
    lv_obj_remove_flag(ui_Label5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_Label5, &ui_img_arrow_down_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLed19 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_lblLed19, 30);
    lv_obj_set_height(ui_lblLed19, 30);
    lv_obj_set_x(ui_lblLed19, 68);
    lv_obj_set_y(ui_lblLed19, 11);
    lv_obj_set_align(ui_lblLed19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed19, "");
    lv_obj_remove_flag(ui_lblLed19, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed19, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed19, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed19, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed13 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_lblLed13, 30);
    lv_obj_set_height(ui_lblLed13, 30);
    lv_obj_set_x(ui_lblLed13, 68);
    lv_obj_set_y(ui_lblLed13, 11);
    lv_obj_set_align(ui_lblLed13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed13, "");
    lv_obj_remove_flag(ui_lblLed13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed13, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed13, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed13, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed14 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_lblLed14, 30);
    lv_obj_set_height(ui_lblLed14, 30);
    lv_obj_set_x(ui_lblLed14, 68);
    lv_obj_set_y(ui_lblLed14, 11);
    lv_obj_set_align(ui_lblLed14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed14, "");
    lv_obj_remove_flag(ui_lblLed14, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed14, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed14, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed14, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed14, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed15 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_lblLed15, 30);
    lv_obj_set_height(ui_lblLed15, 30);
    lv_obj_set_x(ui_lblLed15, 68);
    lv_obj_set_y(ui_lblLed15, 11);
    lv_obj_set_align(ui_lblLed15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed15, "");
    lv_obj_remove_flag(ui_lblLed15, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed15, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed15, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed15, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed16 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_lblLed16, 30);
    lv_obj_set_height(ui_lblLed16, 30);
    lv_obj_set_x(ui_lblLed16, 68);
    lv_obj_set_y(ui_lblLed16, 11);
    lv_obj_set_align(ui_lblLed16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed16, "");
    lv_obj_remove_flag(ui_lblLed16, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed16, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed16, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed16, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed16, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed17 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_lblLed17, 30);
    lv_obj_set_height(ui_lblLed17, 30);
    lv_obj_set_x(ui_lblLed17, 68);
    lv_obj_set_y(ui_lblLed17, 11);
    lv_obj_set_align(ui_lblLed17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed17, "");
    lv_obj_remove_flag(ui_lblLed17, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed17, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed17, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed17, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container8 = lv_obj_create(ui_HelpScreen);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 65);
    lv_obj_set_height(ui_Container8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container8, -39);
    lv_obj_set_y(ui_Container8, 8);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_Container8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLed25 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_lblLed25, 30);
    lv_obj_set_height(ui_lblLed25, 30);
    lv_obj_set_x(ui_lblLed25, 68);
    lv_obj_set_y(ui_lblLed25, 11);
    lv_obj_set_align(ui_lblLed25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed25, "");
    lv_obj_remove_flag(ui_lblLed25, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed25, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed25, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed25, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed25, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed18 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_lblLed18, 30);
    lv_obj_set_height(ui_lblLed18, 30);
    lv_obj_set_x(ui_lblLed18, 68);
    lv_obj_set_y(ui_lblLed18, 11);
    lv_obj_set_align(ui_lblLed18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed18, "");
    lv_obj_remove_flag(ui_lblLed18, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed18, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed18, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed18, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed18, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed20 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_lblLed20, 30);
    lv_obj_set_height(ui_lblLed20, 30);
    lv_obj_set_x(ui_lblLed20, 68);
    lv_obj_set_y(ui_lblLed20, 11);
    lv_obj_set_align(ui_lblLed20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed20, "");
    lv_obj_remove_flag(ui_lblLed20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed20, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed20, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed20, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed20, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed21 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_lblLed21, 30);
    lv_obj_set_height(ui_lblLed21, 30);
    lv_obj_set_x(ui_lblLed21, 68);
    lv_obj_set_y(ui_lblLed21, 11);
    lv_obj_set_align(ui_lblLed21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed21, "");
    lv_obj_remove_flag(ui_lblLed21, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed21, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed21, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed21, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed21, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed22 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_lblLed22, 30);
    lv_obj_set_height(ui_lblLed22, 30);
    lv_obj_set_x(ui_lblLed22, 68);
    lv_obj_set_y(ui_lblLed22, 11);
    lv_obj_set_align(ui_lblLed22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed22, "");
    lv_obj_remove_flag(ui_lblLed22, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed22, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed22, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed22, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed22, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed23 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_lblLed23, 30);
    lv_obj_set_height(ui_lblLed23, 30);
    lv_obj_set_x(ui_lblLed23, 68);
    lv_obj_set_y(ui_lblLed23, 11);
    lv_obj_set_align(ui_lblLed23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed23, "");
    lv_obj_remove_flag(ui_lblLed23, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed23, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed23, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed23, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed23, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label9 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label9, 30);
    lv_obj_set_height(ui_Label9, 30);
    lv_obj_set_x(ui_Label9, 68);
    lv_obj_set_y(ui_Label9, 11);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "");
    lv_obj_remove_flag(ui_Label9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_Label9, &ui_img_arrow_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label6, 30);
    lv_obj_set_height(ui_Label6, 30);
    lv_obj_set_x(ui_Label6, 68);
    lv_obj_set_y(ui_Label6, 11);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "2");
    lv_obj_remove_flag(ui_Label6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_HelpScreen);
    lv_obj_set_width(ui_Label13, 70);
    lv_obj_set_height(ui_Label13, 70);
    lv_obj_set_x(ui_Label13, 68);
    lv_obj_set_y(ui_Label13, 11);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "");
    lv_obj_remove_flag(ui_Label13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_Label13, &ui_img_rotate_right_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_HelpScreen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 280);
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container6, -39);
    lv_obj_set_y(ui_Container6, 8);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label8, 30);
    lv_obj_set_height(ui_Label8, 30);
    lv_obj_set_x(ui_Label8, 68);
    lv_obj_set_y(ui_Label8, 11);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "");
    lv_obj_remove_flag(ui_Label8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_Label8, &ui_img_arrow_right_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLed24 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed24, 30);
    lv_obj_set_height(ui_lblLed24, 30);
    lv_obj_set_x(ui_lblLed24, 68);
    lv_obj_set_y(ui_lblLed24, 11);
    lv_obj_set_align(ui_lblLed24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed24, "");
    lv_obj_remove_flag(ui_lblLed24, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed24, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed24, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed24, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed24, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed26 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed26, 30);
    lv_obj_set_height(ui_lblLed26, 30);
    lv_obj_set_x(ui_lblLed26, 68);
    lv_obj_set_y(ui_lblLed26, 11);
    lv_obj_set_align(ui_lblLed26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed26, "");
    lv_obj_remove_flag(ui_lblLed26, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed26, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed26, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed26, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed26, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed27 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed27, 30);
    lv_obj_set_height(ui_lblLed27, 30);
    lv_obj_set_x(ui_lblLed27, 68);
    lv_obj_set_y(ui_lblLed27, 11);
    lv_obj_set_align(ui_lblLed27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed27, "");
    lv_obj_remove_flag(ui_lblLed27, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed27, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed27, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed27, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed27, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label10 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label10, 30);
    lv_obj_set_height(ui_Label10, 30);
    lv_obj_set_x(ui_Label10, 68);
    lv_obj_set_y(ui_Label10, 11);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "");
    lv_obj_remove_flag(ui_Label10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_Label10, &ui_img_arrow_right_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLed28 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed28, 30);
    lv_obj_set_height(ui_lblLed28, 30);
    lv_obj_set_x(ui_lblLed28, 68);
    lv_obj_set_y(ui_lblLed28, 11);
    lv_obj_set_align(ui_lblLed28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed28, "");
    lv_obj_remove_flag(ui_lblLed28, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed28, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed28, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed28, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed28, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed29 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed29, 30);
    lv_obj_set_height(ui_lblLed29, 30);
    lv_obj_set_x(ui_lblLed29, 68);
    lv_obj_set_y(ui_lblLed29, 11);
    lv_obj_set_align(ui_lblLed29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed29, "");
    lv_obj_remove_flag(ui_lblLed29, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed29, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed29, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed29, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed29, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed30 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed30, 30);
    lv_obj_set_height(ui_lblLed30, 30);
    lv_obj_set_x(ui_lblLed30, 68);
    lv_obj_set_y(ui_lblLed30, 11);
    lv_obj_set_align(ui_lblLed30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed30, "");
    lv_obj_remove_flag(ui_lblLed30, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed30, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed30, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed30, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed30, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label11 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label11, 30);
    lv_obj_set_height(ui_Label11, 30);
    lv_obj_set_x(ui_Label11, 68);
    lv_obj_set_y(ui_Label11, 12);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "1");
    lv_obj_remove_flag(ui_Label11, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLed31 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed31, 30);
    lv_obj_set_height(ui_lblLed31, 30);
    lv_obj_set_x(ui_lblLed31, 68);
    lv_obj_set_y(ui_lblLed31, 11);
    lv_obj_set_align(ui_lblLed31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed31, "");
    lv_obj_remove_flag(ui_lblLed31, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed31, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed31, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed31, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed31, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed32 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed32, 30);
    lv_obj_set_height(ui_lblLed32, 30);
    lv_obj_set_x(ui_lblLed32, 68);
    lv_obj_set_y(ui_lblLed32, 11);
    lv_obj_set_align(ui_lblLed32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed32, "");
    lv_obj_remove_flag(ui_lblLed32, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed32, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed32, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed32, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed32, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed33 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed33, 30);
    lv_obj_set_height(ui_lblLed33, 30);
    lv_obj_set_x(ui_lblLed33, 68);
    lv_obj_set_y(ui_lblLed33, 11);
    lv_obj_set_align(ui_lblLed33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed33, "");
    lv_obj_remove_flag(ui_lblLed33, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed33, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed33, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed33, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed33, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label12 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label12, 30);
    lv_obj_set_height(ui_Label12, 30);
    lv_obj_set_x(ui_Label12, 68);
    lv_obj_set_y(ui_Label12, 12);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "2");
    lv_obj_remove_flag(ui_Label12, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLed34 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed34, 30);
    lv_obj_set_height(ui_lblLed34, 30);
    lv_obj_set_x(ui_lblLed34, 68);
    lv_obj_set_y(ui_lblLed34, 11);
    lv_obj_set_align(ui_lblLed34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed34, "");
    lv_obj_remove_flag(ui_lblLed34, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed34, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed34, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed34, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed34, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed35 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed35, 30);
    lv_obj_set_height(ui_lblLed35, 30);
    lv_obj_set_x(ui_lblLed35, 68);
    lv_obj_set_y(ui_lblLed35, 11);
    lv_obj_set_align(ui_lblLed35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed35, "");
    lv_obj_remove_flag(ui_lblLed35, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed35, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed35, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed35, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed35, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblLed36 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblLed36, 30);
    lv_obj_set_height(ui_lblLed36, 30);
    lv_obj_set_x(ui_lblLed36, 68);
    lv_obj_set_y(ui_lblLed36, 11);
    lv_obj_set_align(ui_lblLed36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLed36, "");
    lv_obj_remove_flag(ui_lblLed36, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_lblLed36, lv_color_hex(0x005A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblLed36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblLed36, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblLed36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblLed36, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblLed36, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lblLed36, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_btnBack, ui_event_btnBack, LV_EVENT_ALL, NULL);

}

void ui_HelpScreen_screen_destroy(void)
{
    if(ui_HelpScreen) lv_obj_del(ui_HelpScreen);

    // NULL screen variables
    ui_HelpScreen = NULL;
    ui_btnBack = NULL;
    ui_Label14 = NULL;
    ui_Container7 = NULL;
    ui_Label7 = NULL;
    ui_Label5 = NULL;
    ui_lblLed19 = NULL;
    ui_lblLed13 = NULL;
    ui_lblLed14 = NULL;
    ui_lblLed15 = NULL;
    ui_lblLed16 = NULL;
    ui_lblLed17 = NULL;
    ui_Container8 = NULL;
    ui_lblLed25 = NULL;
    ui_lblLed18 = NULL;
    ui_lblLed20 = NULL;
    ui_lblLed21 = NULL;
    ui_lblLed22 = NULL;
    ui_lblLed23 = NULL;
    ui_Label9 = NULL;
    ui_Label6 = NULL;
    ui_Label13 = NULL;
    ui_Container6 = NULL;
    ui_Label8 = NULL;
    ui_lblLed24 = NULL;
    ui_lblLed26 = NULL;
    ui_lblLed27 = NULL;
    ui_Label10 = NULL;
    ui_lblLed28 = NULL;
    ui_lblLed29 = NULL;
    ui_lblLed30 = NULL;
    ui_Label11 = NULL;
    ui_lblLed31 = NULL;
    ui_lblLed32 = NULL;
    ui_lblLed33 = NULL;
    ui_Label12 = NULL;
    ui_lblLed34 = NULL;
    ui_lblLed35 = NULL;
    ui_lblLed36 = NULL;

}
