// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_INFORMATION_H
#define UI_INFORMATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Information
extern void ui_Information_screen_init(void);
extern void ui_Information_screen_destroy(void);
extern lv_obj_t * ui_Information;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

