// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"

lv_obj_t * ui_LoadScreen = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_barLoadProgress = NULL;
// event funtions
void ui_event_LoadScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadScreen_OnLoaded(e);
    }
}

// build funtions

void ui_LoadScreen_screen_init(void)
{
    ui_LoadScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LoadScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_LoadScreen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_LoadScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LoadScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LoadScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LoadScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LoadScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LoadScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoadScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_LoadScreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image1 = lv_image_create(ui_LoadScreen);
    lv_image_set_src(ui_Image1, &ui_img_load_screen_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -58);
    lv_obj_set_y(ui_Image1, -35);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_barLoadProgress = lv_bar_create(ui_LoadScreen);
    lv_bar_set_range(ui_barLoadProgress, 0, 5000);
    lv_obj_set_width(ui_barLoadProgress, 310);
    lv_obj_set_height(ui_barLoadProgress, 15);
    lv_obj_set_x(ui_barLoadProgress, 65);
    lv_obj_set_y(ui_barLoadProgress, 94);
    lv_obj_set_align(ui_barLoadProgress, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_barLoadProgress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barLoadProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_barLoadProgress, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barLoadProgress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barLoadProgress, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barLoadProgress,
                                                                                                      lv_obj_get_style_pad_right(ui_barLoadProgress, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_LoadScreen, ui_event_LoadScreen, LV_EVENT_ALL, NULL);

}

void ui_LoadScreen_screen_destroy(void)
{
    if(ui_LoadScreen) lv_obj_del(ui_LoadScreen);

    // NULL screen variables
    ui_LoadScreen = NULL;
    ui_Image1 = NULL;
    ui_barLoadProgress = NULL;

}
