// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"

lv_obj_t * ui_Login = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_TextArea = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_TextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Login_OnTextAreaEdit(e);
    }
    if(event_code == LV_EVENT_READY) {
        Login_OnTextAreaEdit(e);
    }
}

// build funtions

void ui_Login_screen_init(void)
{
    ui_Login = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Login, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Login, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Login, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Login, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Login, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Login, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label4 = lv_label_create(ui_Login);
    lv_obj_set_width(ui_Label4, 300);
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -95);
    lv_obj_set_y(ui_Label4, -89);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Enter verification code");
    lv_obj_remove_flag(ui_Label4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea = lv_textarea_create(ui_Login);
    lv_obj_set_width(ui_TextArea, 120);
    lv_obj_set_height(ui_TextArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextArea, -44);
    lv_obj_set_y(ui_TextArea, -44);
    lv_obj_set_align(ui_TextArea, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextArea, NULL);
    else lv_textarea_set_accepted_chars(ui_TextArea, "0123456789");
    lv_textarea_set_max_length(ui_TextArea, 3);
    lv_textarea_set_one_line(ui_TextArea, true);
    lv_obj_add_state(ui_TextArea, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_TextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC);     /// Flags
    lv_obj_set_style_text_align(ui_TextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Login);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 180);
    lv_obj_set_height(ui_Keyboard1, 200);
    lv_obj_set_x(ui_Keyboard1, 8);
    lv_obj_set_y(ui_Keyboard1, 73);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Keyboard1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea);

}

void ui_Login_screen_destroy(void)
{
    if(ui_Login) lv_obj_del(ui_Login);

    // NULL screen variables
    ui_Login = NULL;
    ui_Label4 = NULL;
    ui_TextArea = NULL;
    ui_Keyboard1 = NULL;

}
