// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_LOADSCREEN_H
#define UI_LOADSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LoadScreen
extern void ui_LoadScreen_screen_init(void);
extern void ui_LoadScreen_screen_destroy(void);
extern void ui_event_LoadScreen(lv_event_t * e);
extern lv_obj_t * ui_LoadScreen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_barLoadProgress;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

