// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_LOGIN_H
#define UI_LOGIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Login
extern void ui_Login_screen_init(void);
extern void ui_Login_screen_destroy(void);
extern lv_obj_t * ui_Login;
extern lv_obj_t * ui_Label4;
extern void ui_event_TextArea(lv_event_t * e);
extern lv_obj_t * ui_TextArea;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

