// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Mazes_Project

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_chartBgImg = NULL;
lv_obj_t * ui_chartGrid = NULL;
lv_obj_t * ui_chartGrid_Xaxis = NULL;
lv_obj_t * ui_chartGrid_Yaxis1 = NULL;
lv_obj_t * ui_chartGrid_Yaxis2 = NULL;
lv_obj_t * ui_chartIndicator = NULL;
lv_obj_t * ui_chartIndicator_Xaxis = NULL;
lv_obj_t * ui_chartIndicator_Yaxis1 = NULL;
lv_obj_t * ui_chartIndicator_Yaxis2 = NULL;
lv_obj_t * ui_chartNavigator = NULL;
lv_obj_t * ui_chartNavigator_Xaxis = NULL;
lv_obj_t * ui_chartNavigator_Yaxis1 = NULL;
lv_obj_t * ui_chartNavigator_Yaxis2 = NULL;
lv_obj_t * ui_chartMover = NULL;
lv_obj_t * ui_chartMover_Xaxis = NULL;
lv_obj_t * ui_chartMover_Yaxis1 = NULL;
lv_obj_t * ui_chartMover_Yaxis2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_btnUp = NULL;
lv_obj_t * ui_btnLeft = NULL;
lv_obj_t * ui_btnRight = NULL;
lv_obj_t * ui_btnDown = NULL;
lv_obj_t * ui_imgResult = NULL;
lv_obj_t * ui_sldBrightness = NULL;
lv_obj_t * ui_wndTransparent = NULL;
// event funtions
void ui_event_btnUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnButtonClick(e);
    }
}

void ui_event_btnLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnButtonClick(e);
    }
}

void ui_event_btnRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnButtonClick(e);
    }
}

void ui_event_btnDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnButtonClick(e);
    }
}

void ui_event_sldBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnBrightnessChange(e);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Main, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Main, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 210);
    lv_obj_set_height(ui_Container1, 210);
    lv_obj_set_x(ui_Container1, 5);
    lv_obj_set_y(ui_Container1, 14);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x000037), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chartBgImg = lv_image_create(ui_Container1);
    lv_obj_set_width(ui_chartBgImg, 210);
    lv_obj_set_height(ui_chartBgImg, 210);
    lv_obj_set_align(ui_chartBgImg, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_chartBgImg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_chartBgImg, &ui_img_maze0_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_chartBgImg, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_chartBgImg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chartGrid = lv_chart_create(ui_Container1);
    lv_obj_set_width(ui_chartGrid, 210);
    lv_obj_set_height(ui_chartGrid, 210);
    lv_obj_set_align(ui_chartGrid, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chartGrid, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_chartGrid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_chartGrid, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_chartGrid, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_chartGrid, LV_CHART_TYPE_SCATTER);
    lv_chart_set_point_count(ui_chartGrid, 100);
    lv_chart_set_range(ui_chartGrid, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
    lv_chart_set_range(ui_chartGrid, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_chartGrid, 6, 6);
    lv_obj_set_style_bg_color(ui_chartGrid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chartGrid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_chartGrid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chartGrid, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chartGrid, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chartGrid, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chartGrid, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chartGrid_Xaxis = lv_scale_create(ui_chartGrid);
    lv_scale_set_mode(ui_chartGrid_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_chartGrid_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_chartGrid_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartGrid_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_chartGrid_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartGrid_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_chartGrid_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_chartGrid_Xaxis, 0, 1 > 0 ? 1 - 1 : 0);
    lv_scale_set_total_tick_count(ui_chartGrid_Xaxis, (1 > 0 ? 1 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_chartGrid_Xaxis, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_chartGrid_Xaxis, false);
    ui_chartGrid_Yaxis1 = lv_scale_create(ui_chartGrid);
    lv_scale_set_mode(ui_chartGrid_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_chartGrid_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_chartGrid_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartGrid_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartGrid_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartGrid_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartGrid_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_chartGrid_Yaxis1,  0, 0);
    lv_scale_set_total_tick_count(ui_chartGrid_Yaxis1, (1 > 0 ? 1 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_chartGrid_Yaxis1, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_chartGrid_Yaxis1, false);
    ui_chartGrid_Yaxis2 = lv_scale_create(ui_chartGrid);
    lv_scale_set_mode(ui_chartGrid_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_chartGrid_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_chartGrid_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartGrid_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartGrid_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartGrid_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartGrid_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_chartGrid_Yaxis2,  0, 0);
    lv_scale_set_total_tick_count(ui_chartGrid_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_chartGrid_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_chartGrid_Yaxis2, false);

    lv_obj_set_style_radius(ui_chartGrid, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_chartGrid, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_chartGrid, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_chartGrid, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_chartGrid, 15, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_chartGrid, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_chartIndicator = lv_chart_create(ui_Container1);
    lv_obj_set_width(ui_chartIndicator, 210);
    lv_obj_set_height(ui_chartIndicator, 210);
    lv_obj_set_align(ui_chartIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chartIndicator, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_chartIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_chartIndicator,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_chartIndicator, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_chartIndicator, LV_CHART_TYPE_SCATTER);
    lv_chart_set_point_count(ui_chartIndicator, 100);
    lv_chart_set_range(ui_chartIndicator, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
    lv_chart_set_range(ui_chartIndicator, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_chartIndicator, 6, 6);
    lv_obj_set_style_bg_color(ui_chartIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chartIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_chartIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chartIndicator, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chartIndicator, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chartIndicator, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chartIndicator, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chartIndicator_Xaxis = lv_scale_create(ui_chartIndicator);
    lv_scale_set_mode(ui_chartIndicator_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_chartIndicator_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_chartIndicator_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartIndicator_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_chartIndicator_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartIndicator_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_chartIndicator_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_chartIndicator_Xaxis, 0, 1 > 0 ? 1 - 1 : 0);
    lv_scale_set_total_tick_count(ui_chartIndicator_Xaxis, (1 > 0 ? 1 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_chartIndicator_Xaxis, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_chartIndicator_Xaxis, false);
    ui_chartIndicator_Yaxis1 = lv_scale_create(ui_chartIndicator);
    lv_scale_set_mode(ui_chartIndicator_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_chartIndicator_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_chartIndicator_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartIndicator_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartIndicator_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartIndicator_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartIndicator_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_chartIndicator_Yaxis1,  0, 0);
    lv_scale_set_total_tick_count(ui_chartIndicator_Yaxis1, (1 > 0 ? 1 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_chartIndicator_Yaxis1, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_chartIndicator_Yaxis1, false);
    ui_chartIndicator_Yaxis2 = lv_scale_create(ui_chartIndicator);
    lv_scale_set_mode(ui_chartIndicator_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_chartIndicator_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_chartIndicator_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartIndicator_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartIndicator_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartIndicator_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartIndicator_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_chartIndicator_Yaxis2,  0, 0);
    lv_scale_set_total_tick_count(ui_chartIndicator_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_chartIndicator_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_chartIndicator_Yaxis2, false);

    lv_obj_set_style_radius(ui_chartIndicator, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_chartIndicator, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chartIndicator, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_chartIndicator, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_chartIndicator, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_chartIndicator, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_chartIndicator, 30, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_chartIndicator, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_chartNavigator = lv_chart_create(ui_Container1);
    lv_obj_set_width(ui_chartNavigator, 210);
    lv_obj_set_height(ui_chartNavigator, 210);
    lv_obj_set_align(ui_chartNavigator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chartNavigator, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_chartNavigator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_chartNavigator,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_chartNavigator, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_chartNavigator, LV_CHART_TYPE_SCATTER);
    lv_chart_set_point_count(ui_chartNavigator, 100);
    lv_chart_set_range(ui_chartNavigator, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
    lv_chart_set_range(ui_chartNavigator, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_chartNavigator, 6, 6);
    lv_obj_set_style_bg_color(ui_chartNavigator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chartNavigator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_chartNavigator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chartNavigator, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chartNavigator, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chartNavigator, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chartNavigator, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chartNavigator_Xaxis = lv_scale_create(ui_chartNavigator);
    lv_scale_set_mode(ui_chartNavigator_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_chartNavigator_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_chartNavigator_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartNavigator_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_chartNavigator_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartNavigator_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_chartNavigator_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_chartNavigator_Xaxis, 0, 1 > 0 ? 1 - 1 : 0);
    lv_scale_set_total_tick_count(ui_chartNavigator_Xaxis, (1 > 0 ? 1 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_chartNavigator_Xaxis, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_chartNavigator_Xaxis, false);
    ui_chartNavigator_Yaxis1 = lv_scale_create(ui_chartNavigator);
    lv_scale_set_mode(ui_chartNavigator_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_chartNavigator_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_chartNavigator_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartNavigator_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartNavigator_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartNavigator_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartNavigator_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_chartNavigator_Yaxis1,  0, 0);
    lv_scale_set_total_tick_count(ui_chartNavigator_Yaxis1, (1 > 0 ? 1 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_chartNavigator_Yaxis1, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_chartNavigator_Yaxis1, false);
    ui_chartNavigator_Yaxis2 = lv_scale_create(ui_chartNavigator);
    lv_scale_set_mode(ui_chartNavigator_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_chartNavigator_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_chartNavigator_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartNavigator_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartNavigator_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartNavigator_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartNavigator_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_chartNavigator_Yaxis2,  0, 0);
    lv_scale_set_total_tick_count(ui_chartNavigator_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_chartNavigator_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_chartNavigator_Yaxis2, false);

    lv_obj_set_style_bg_color(ui_chartNavigator, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chartNavigator, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_chartNavigator, &ui_img_assistant_navigation_png,
                                  LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_chartNavigator, 15, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_chartNavigator, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_chartMover = lv_chart_create(ui_Container1);
    lv_obj_set_width(ui_chartMover, 210);
    lv_obj_set_height(ui_chartMover, 210);
    lv_obj_set_align(ui_chartMover, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chartMover, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_chartMover, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_chartMover, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_chartMover, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_chartMover, LV_CHART_TYPE_SCATTER);
    lv_chart_set_point_count(ui_chartMover, 100);
    lv_chart_set_range(ui_chartMover, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
    lv_chart_set_range(ui_chartMover, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_chartMover, 6, 6);
    lv_obj_set_style_bg_color(ui_chartMover, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chartMover, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_chartMover, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chartMover, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chartMover, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chartMover, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chartMover, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chartMover_Xaxis = lv_scale_create(ui_chartMover);
    lv_scale_set_mode(ui_chartMover_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_chartMover_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_chartMover_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartMover_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_chartMover_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartMover_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_chartMover_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_chartMover_Xaxis, 0, 1 > 0 ? 1 - 1 : 0);
    lv_scale_set_total_tick_count(ui_chartMover_Xaxis, (1 > 0 ? 1 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_chartMover_Xaxis, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_chartMover_Xaxis, false);
    ui_chartMover_Yaxis1 = lv_scale_create(ui_chartMover);
    lv_scale_set_mode(ui_chartMover_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_chartMover_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_chartMover_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartMover_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartMover_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartMover_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartMover_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_chartMover_Yaxis1,  0, 0);
    lv_scale_set_total_tick_count(ui_chartMover_Yaxis1, (1 > 0 ? 1 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_chartMover_Yaxis1, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_chartMover_Yaxis1, false);
    ui_chartMover_Yaxis2 = lv_scale_create(ui_chartMover);
    lv_scale_set_mode(ui_chartMover_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_chartMover_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_chartMover_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartMover_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartMover_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartMover_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartMover_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_chartMover_Yaxis2,  0, 0);
    lv_scale_set_total_tick_count(ui_chartMover_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_chartMover_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_chartMover_Yaxis2, false);

    lv_obj_set_style_radius(ui_chartMover, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_chartMover, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_chartMover, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_chartMover, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_chartMover, 15, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_chartMover, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Container2 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 90);
    lv_obj_set_height(ui_Container2, 210);
    lv_obj_set_x(ui_Container2, 5);
    lv_obj_set_y(ui_Container2, 14);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnUp = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnUp, 80);
    lv_obj_set_height(ui_btnUp, 45);
    lv_obj_set_align(ui_btnUp, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnUp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnUp, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnUp, &ui_img_arrow_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnUp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnLeft = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnLeft, 80);
    lv_obj_set_height(ui_btnLeft, 45);
    lv_obj_set_align(ui_btnLeft, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnLeft, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnLeft, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnLeft, &ui_img_arrow_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnLeft, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnLeft, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRight = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnRight, 80);
    lv_obj_set_height(ui_btnRight, 45);
    lv_obj_set_align(ui_btnRight, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRight, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRight, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRight, &ui_img_arrow_right_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRight, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnDown = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnDown, 80);
    lv_obj_set_height(ui_btnDown, 45);
    lv_obj_set_align(ui_btnDown, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnDown, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnDown, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnDown, &ui_img_arrow_down_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnDown, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgResult = lv_image_create(ui_Main);
    lv_obj_set_width(ui_imgResult, 320);
    lv_obj_set_height(ui_imgResult, 240);
    lv_obj_set_align(ui_imgResult, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgResult, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_remove_flag(ui_imgResult, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_imgResult, &ui_img_success_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_src(ui_imgResult, &ui_img_fail_png, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_sldBrightness = lv_slider_create(ui_Main);
    lv_slider_set_range(ui_sldBrightness, 10, 255);
    lv_slider_set_value(ui_sldBrightness, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldBrightness, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_sldBrightness, 300);
    lv_obj_set_height(ui_sldBrightness, 10);
    lv_obj_set_x(ui_sldBrightness, -135);
    lv_obj_set_y(ui_sldBrightness, -9);
    lv_obj_set_align(ui_sldBrightness, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_sldBrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sldBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sldBrightness, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_sldBrightness, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sldBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sldBrightness, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_sldBrightness, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sldBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sldBrightness, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sldBrightness, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sldBrightness,
                                                                                                    lv_obj_get_style_pad_right(ui_sldBrightness, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_wndTransparent = lv_label_create(ui_Main);
    lv_obj_set_width(ui_wndTransparent, 320);
    lv_obj_set_height(ui_wndTransparent, 240);
    lv_obj_set_align(ui_wndTransparent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wndTransparent, "");
    lv_obj_add_flag(ui_wndTransparent, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE |
                    LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_wndTransparent,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_add_event_cb(ui_btnUp, ui_event_btnUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnLeft, ui_event_btnLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRight, ui_event_btnRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnDown, ui_event_btnDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldBrightness, ui_event_sldBrightness, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_Container1 = NULL;
    ui_chartBgImg = NULL;
    ui_chartGrid = NULL;
    ui_chartIndicator = NULL;
    ui_chartNavigator = NULL;
    ui_chartMover = NULL;
    ui_Container2 = NULL;
    ui_btnUp = NULL;
    ui_btnLeft = NULL;
    ui_btnRight = NULL;
    ui_btnDown = NULL;
    ui_imgResult = NULL;
    ui_sldBrightness = NULL;
    ui_wndTransparent = NULL;

}
