// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Memory_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_lblDisplay;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_lblButtonText1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_lblButtonText2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_lblButtonText3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_lblButtonText4;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_barStage;
extern lv_obj_t * ui_lblBarValue;
extern lv_obj_t * ui_imgResult;
extern void ui_event_sldBrightness(lv_event_t * e);
extern lv_obj_t * ui_sldBrightness;
extern lv_obj_t * ui_wndTransparent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

