// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SystemInfo_Project

#ifndef UI_MAIN1_H
#define UI_MAIN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main1
extern void ui_Main1_screen_init(void);
extern void ui_Main1_screen_destroy(void);
extern void ui_event_Main1(lv_event_t * e);
extern lv_obj_t * ui_Main1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_lblIndicator;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_lblSerial;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

