// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern void ui_event_lblStrike(lv_event_t * e);
extern lv_obj_t * ui_lblStrike;
extern void ui_event_btnPlay(lv_event_t * e);
extern lv_obj_t * ui_btnPlay;
extern void ui_event_btnMainToScore(lv_event_t * e);
extern lv_obj_t * ui_btnMainToScore;
extern void ui_event_btnScore1(lv_event_t * e);
extern lv_obj_t * ui_btnScore1;
extern lv_obj_t * ui_lblEndlessTimer;
extern lv_obj_t * ui_lblTimer;
extern void ui_event_sldBrightness(lv_event_t * e);
extern lv_obj_t * ui_sldBrightness;
extern lv_obj_t * ui_lblBlack;
extern lv_obj_t * ui_lblTransparent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

