// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_MODULESELECT_H
#define UI_MODULESELECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ModuleSelect
extern void ui_ModuleSelect_screen_init(void);
extern void ui_ModuleSelect_screen_destroy(void);
extern lv_obj_t * ui_ModuleSelect;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container1;
extern void ui_event_cbSettingModule1(lv_event_t * e);
extern lv_obj_t * ui_cbSettingModule1;
extern lv_obj_t * ui_cbSettingModule2;
extern lv_obj_t * ui_cbSettingModule3;
extern lv_obj_t * ui_cbSettingModule4;
extern lv_obj_t * ui_cbSettingModule5;
extern lv_obj_t * ui_cbSettingModule6;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_cbSettingModule7;
extern lv_obj_t * ui_cbSettingModule8;
extern lv_obj_t * ui_cbSettingModule9;
extern lv_obj_t * ui_cbSettingModule10;
extern lv_obj_t * ui_cbSettingModule11;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_cbSettingNeedyModule1;
extern lv_obj_t * ui_cbSettingNeedyModule2;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_cbSettingNeedyModule3;
extern void ui_event_btnSettingBack(lv_event_t * e);
extern lv_obj_t * ui_btnSettingBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

