// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"

lv_obj_t * ui_OrderPlay = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_cbOPModule1 = NULL;
lv_obj_t * ui_cbOPModule2 = NULL;
lv_obj_t * ui_cbOPModule3 = NULL;
lv_obj_t * ui_cbOPModule4 = NULL;
lv_obj_t * ui_cbOPModule5 = NULL;
lv_obj_t * ui_cbOPModule6 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_cbOPModule7 = NULL;
lv_obj_t * ui_cbOPModule8 = NULL;
lv_obj_t * ui_cbOPModule9 = NULL;
lv_obj_t * ui_cbOPModule10 = NULL;
lv_obj_t * ui_cbOPModule11 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_cbOPNeedyModule1 = NULL;
lv_obj_t * ui_cbOPNeedyModule2 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_cbOPNeedyModule3 = NULL;
lv_obj_t * ui_btnOPBack = NULL;
// event funtions
void ui_event_OrderPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        OrderPlay_OnLoaded(e);
    }
}

void ui_event_btnOPBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_OrderPlay_screen_init(void)
{
    ui_OrderPlay = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_OrderPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_OrderPlay, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_OrderPlay, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_OrderPlay, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OrderPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_OrderPlay, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_OrderPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_OrderPlay);
    lv_obj_set_width(ui_Panel3, 315);
    lv_obj_set_height(ui_Panel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Panel3, 10);
    lv_obj_set_y(ui_Panel3, 38);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label8, 300);
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -8);
    lv_obj_set_y(ui_Label8, -89);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Main modules");
    lv_obj_remove_flag(ui_Label8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container6, -68);
    lv_obj_set_y(ui_Container6, 6);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_Container6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cbOPModule1 = lv_checkbox_create(ui_Container6);
    lv_checkbox_set_text(ui_cbOPModule1, "Wires");
    lv_obj_set_width(ui_cbOPModule1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule1, -28);
    lv_obj_set_y(ui_cbOPModule1, -7);
    lv_obj_set_align(ui_cbOPModule1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule2 = lv_checkbox_create(ui_Container6);
    lv_checkbox_set_text(ui_cbOPModule2, "The Button");
    lv_obj_set_width(ui_cbOPModule2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule2, -28);
    lv_obj_set_y(ui_cbOPModule2, -7);
    lv_obj_set_align(ui_cbOPModule2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule2, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule3 = lv_checkbox_create(ui_Container6);
    lv_checkbox_set_text(ui_cbOPModule3, "Keypads");
    lv_obj_set_width(ui_cbOPModule3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule3, -28);
    lv_obj_set_y(ui_cbOPModule3, -7);
    lv_obj_set_align(ui_cbOPModule3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule3, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule4 = lv_checkbox_create(ui_Container6);
    lv_checkbox_set_text(ui_cbOPModule4, "Simon Says");
    lv_obj_set_width(ui_cbOPModule4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule4, -28);
    lv_obj_set_y(ui_cbOPModule4, -7);
    lv_obj_set_align(ui_cbOPModule4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule4, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule5 = lv_checkbox_create(ui_Container6);
    lv_checkbox_set_text(ui_cbOPModule5, "Who's on First");
    lv_obj_set_width(ui_cbOPModule5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule5, -28);
    lv_obj_set_y(ui_cbOPModule5, -7);
    lv_obj_set_align(ui_cbOPModule5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule5, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule6 = lv_checkbox_create(ui_Container6);
    lv_checkbox_set_text(ui_cbOPModule6, "Memory");
    lv_obj_set_width(ui_cbOPModule6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule6, -28);
    lv_obj_set_y(ui_cbOPModule6, -7);
    lv_obj_set_align(ui_cbOPModule6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule6, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Container7 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container7, 57);
    lv_obj_set_y(ui_Container7, -72);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_Container7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cbOPModule7 = lv_checkbox_create(ui_Container7);
    lv_checkbox_set_text(ui_cbOPModule7, "Morse Code");
    lv_obj_set_width(ui_cbOPModule7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule7, -28);
    lv_obj_set_y(ui_cbOPModule7, -7);
    lv_obj_set_align(ui_cbOPModule7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule7, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule7, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule8 = lv_checkbox_create(ui_Container7);
    lv_checkbox_set_text(ui_cbOPModule8, "Complicated Wires");
    lv_obj_set_width(ui_cbOPModule8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule8, -28);
    lv_obj_set_y(ui_cbOPModule8, -7);
    lv_obj_set_align(ui_cbOPModule8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_align(ui_cbOPModule8, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cbOPModule8, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule8, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule9 = lv_checkbox_create(ui_Container7);
    lv_checkbox_set_text(ui_cbOPModule9, "Wire Sequences");
    lv_obj_set_width(ui_cbOPModule9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule9, -28);
    lv_obj_set_y(ui_cbOPModule9, -7);
    lv_obj_set_align(ui_cbOPModule9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule9, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule9, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule10 = lv_checkbox_create(ui_Container7);
    lv_checkbox_set_text(ui_cbOPModule10, "Mazes");
    lv_obj_set_width(ui_cbOPModule10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule10, -28);
    lv_obj_set_y(ui_cbOPModule10, -7);
    lv_obj_set_align(ui_cbOPModule10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule10, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule10, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPModule11 = lv_checkbox_create(ui_Container7);
    lv_checkbox_set_text(ui_cbOPModule11, "Passwords");
    lv_obj_set_width(ui_cbOPModule11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPModule11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPModule11, -28);
    lv_obj_set_y(ui_cbOPModule11, -7);
    lv_obj_set_align(ui_cbOPModule11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPModule11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPModule11, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPModule11, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Panel4 = lv_obj_create(ui_OrderPlay);
    lv_obj_set_width(ui_Panel4, 315);
    lv_obj_set_height(ui_Panel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Panel4, 10);
    lv_obj_set_y(ui_Panel4, 38);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label14, 300);
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -8);
    lv_obj_set_y(ui_Label14, -89);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Needy modules");
    lv_obj_remove_flag(ui_Label14, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container8, 57);
    lv_obj_set_y(ui_Container8, -72);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_Container8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cbOPNeedyModule1 = lv_checkbox_create(ui_Container8);
    lv_checkbox_set_text(ui_cbOPNeedyModule1, "Venting Gas");
    lv_obj_set_width(ui_cbOPNeedyModule1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPNeedyModule1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPNeedyModule1, -28);
    lv_obj_set_y(ui_cbOPNeedyModule1, -7);
    lv_obj_set_align(ui_cbOPNeedyModule1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPNeedyModule1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPNeedyModule1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPNeedyModule1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_cbOPNeedyModule2 = lv_checkbox_create(ui_Container8);
    lv_checkbox_set_text(ui_cbOPNeedyModule2, "Capacitor Discharge");
    lv_obj_set_width(ui_cbOPNeedyModule2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPNeedyModule2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPNeedyModule2, -28);
    lv_obj_set_y(ui_cbOPNeedyModule2, -7);
    lv_obj_set_align(ui_cbOPNeedyModule2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPNeedyModule2,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPNeedyModule2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPNeedyModule2, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Container9 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container9, 57);
    lv_obj_set_y(ui_Container9, -72);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_Container9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cbOPNeedyModule3 = lv_checkbox_create(ui_Container9);
    lv_checkbox_set_text(ui_cbOPNeedyModule3, "Knobs");
    lv_obj_set_width(ui_cbOPNeedyModule3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cbOPNeedyModule3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbOPNeedyModule3, -28);
    lv_obj_set_y(ui_cbOPNeedyModule3, -7);
    lv_obj_set_align(ui_cbOPNeedyModule3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbOPNeedyModule3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cbOPNeedyModule3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_cbOPNeedyModule3, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_btnOPBack = lv_button_create(ui_OrderPlay);
    lv_obj_set_width(ui_btnOPBack, 45);
    lv_obj_set_height(ui_btnOPBack, 45);
    lv_obj_set_x(ui_btnOPBack, 134);
    lv_obj_set_y(ui_btnOPBack, 94);
    lv_obj_set_align(ui_btnOPBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnOPBack, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnOPBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnOPBack, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOPBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnOPBack, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_btnOPBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_btnOPBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnOPBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnOPBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnOPBack, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnOPBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_btnOPBack, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_width(ui_btnOPBack, 1, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_add_event_cb(ui_btnOPBack, ui_event_btnOPBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OrderPlay, ui_event_OrderPlay, LV_EVENT_ALL, NULL);

}

void ui_OrderPlay_screen_destroy(void)
{
    if(ui_OrderPlay) lv_obj_del(ui_OrderPlay);

    // NULL screen variables
    ui_OrderPlay = NULL;
    ui_Panel3 = NULL;
    ui_Label8 = NULL;
    ui_Container6 = NULL;
    ui_cbOPModule1 = NULL;
    ui_cbOPModule2 = NULL;
    ui_cbOPModule3 = NULL;
    ui_cbOPModule4 = NULL;
    ui_cbOPModule5 = NULL;
    ui_cbOPModule6 = NULL;
    ui_Container7 = NULL;
    ui_cbOPModule7 = NULL;
    ui_cbOPModule8 = NULL;
    ui_cbOPModule9 = NULL;
    ui_cbOPModule10 = NULL;
    ui_cbOPModule11 = NULL;
    ui_Panel4 = NULL;
    ui_Label14 = NULL;
    ui_Container8 = NULL;
    ui_cbOPNeedyModule1 = NULL;
    ui_cbOPNeedyModule2 = NULL;
    ui_Container9 = NULL;
    ui_cbOPNeedyModule3 = NULL;
    ui_btnOPBack = NULL;

}
