// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_ORDERPLAY_H
#define UI_ORDERPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OrderPlay
extern void ui_OrderPlay_screen_init(void);
extern void ui_OrderPlay_screen_destroy(void);
extern void ui_event_OrderPlay(lv_event_t * e);
extern lv_obj_t * ui_OrderPlay;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_cbOPModule1;
extern lv_obj_t * ui_cbOPModule2;
extern lv_obj_t * ui_cbOPModule3;
extern lv_obj_t * ui_cbOPModule4;
extern lv_obj_t * ui_cbOPModule5;
extern lv_obj_t * ui_cbOPModule6;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_cbOPModule7;
extern lv_obj_t * ui_cbOPModule8;
extern lv_obj_t * ui_cbOPModule9;
extern lv_obj_t * ui_cbOPModule10;
extern lv_obj_t * ui_cbOPModule11;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_cbOPNeedyModule1;
extern lv_obj_t * ui_cbOPNeedyModule2;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_cbOPNeedyModule3;
extern void ui_event_btnOPBack(lv_event_t * e);
extern lv_obj_t * ui_btnOPBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

