// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"

void ui_Setting_screen_init(void)
{
    ui_Setting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Setting, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Setting, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Setting);
    lv_obj_set_width(ui_Label6, 300);
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -8);
    lv_obj_set_y(ui_Label6, -89);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Main modules");
    lv_obj_remove_flag(ui_Label6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule1 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule1, 45);
    lv_obj_set_height(ui_btnSettingModule1, 45);
    lv_obj_set_x(ui_btnSettingModule1, -4);
    lv_obj_set_y(ui_btnSettingModule1, -44);
    lv_obj_set_align(ui_btnSettingModule1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_btnSettingModule1, LV_STATE_CHECKED | LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_btnSettingModule1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule2 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule2, 45);
    lv_obj_set_height(ui_btnSettingModule2, 45);
    lv_obj_set_x(ui_btnSettingModule2, -4);
    lv_obj_set_y(ui_btnSettingModule2, -44);
    lv_obj_set_align(ui_btnSettingModule2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule3 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule3, 45);
    lv_obj_set_height(ui_btnSettingModule3, 45);
    lv_obj_set_x(ui_btnSettingModule3, -4);
    lv_obj_set_y(ui_btnSettingModule3, -44);
    lv_obj_set_align(ui_btnSettingModule3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule4 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule4, 45);
    lv_obj_set_height(ui_btnSettingModule4, 45);
    lv_obj_set_x(ui_btnSettingModule4, -4);
    lv_obj_set_y(ui_btnSettingModule4, -44);
    lv_obj_set_align(ui_btnSettingModule4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule5 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule5, 45);
    lv_obj_set_height(ui_btnSettingModule5, 45);
    lv_obj_set_x(ui_btnSettingModule5, -4);
    lv_obj_set_y(ui_btnSettingModule5, -44);
    lv_obj_set_align(ui_btnSettingModule5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule5, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule6 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule6, 45);
    lv_obj_set_height(ui_btnSettingModule6, 45);
    lv_obj_set_x(ui_btnSettingModule6, -4);
    lv_obj_set_y(ui_btnSettingModule6, -44);
    lv_obj_set_align(ui_btnSettingModule6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule6, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule7 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule7, 45);
    lv_obj_set_height(ui_btnSettingModule7, 45);
    lv_obj_set_x(ui_btnSettingModule7, -4);
    lv_obj_set_y(ui_btnSettingModule7, -44);
    lv_obj_set_align(ui_btnSettingModule7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule7, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule8 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule8, 45);
    lv_obj_set_height(ui_btnSettingModule8, 45);
    lv_obj_set_x(ui_btnSettingModule8, -4);
    lv_obj_set_y(ui_btnSettingModule8, -44);
    lv_obj_set_align(ui_btnSettingModule8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule8, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule9 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule9, 45);
    lv_obj_set_height(ui_btnSettingModule9, 45);
    lv_obj_set_x(ui_btnSettingModule9, -4);
    lv_obj_set_y(ui_btnSettingModule9, -44);
    lv_obj_set_align(ui_btnSettingModule9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule9, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule10 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule10, 45);
    lv_obj_set_height(ui_btnSettingModule10, 45);
    lv_obj_set_x(ui_btnSettingModule10, -4);
    lv_obj_set_y(ui_btnSettingModule10, -44);
    lv_obj_set_align(ui_btnSettingModule10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule10, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingModule11 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingModule11, 45);
    lv_obj_set_height(ui_btnSettingModule11, 45);
    lv_obj_set_x(ui_btnSettingModule11, -4);
    lv_obj_set_y(ui_btnSettingModule11, -44);
    lv_obj_set_align(ui_btnSettingModule11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingModule11, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingModule11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingModule11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingModule11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingModule11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Setting);
    lv_obj_set_width(ui_Label3, 300);
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -8);
    lv_obj_set_y(ui_Label3, -89);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Needy modules");
    lv_obj_remove_flag(ui_Label3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingNeedyModule1 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingNeedyModule1, 45);
    lv_obj_set_height(ui_btnSettingNeedyModule1, 45);
    lv_obj_set_x(ui_btnSettingNeedyModule1, -4);
    lv_obj_set_y(ui_btnSettingNeedyModule1, -44);
    lv_obj_set_align(ui_btnSettingNeedyModule1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingNeedyModule1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingNeedyModule1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingNeedyModule1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingNeedyModule1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingNeedyModule1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingNeedyModule2 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingNeedyModule2, 45);
    lv_obj_set_height(ui_btnSettingNeedyModule2, 45);
    lv_obj_set_x(ui_btnSettingNeedyModule2, -4);
    lv_obj_set_y(ui_btnSettingNeedyModule2, -44);
    lv_obj_set_align(ui_btnSettingNeedyModule2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingNeedyModule2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingNeedyModule2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingNeedyModule2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingNeedyModule2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingNeedyModule2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettingNeedyModule3 = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnSettingNeedyModule3, 45);
    lv_obj_set_height(ui_btnSettingNeedyModule3, 45);
    lv_obj_set_x(ui_btnSettingNeedyModule3, -4);
    lv_obj_set_y(ui_btnSettingNeedyModule3, -44);
    lv_obj_set_align(ui_btnSettingNeedyModule3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingNeedyModule3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingNeedyModule3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnSettingNeedyModule3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingNeedyModule3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingNeedyModule3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBack = lv_button_create(ui_Setting);
    lv_obj_set_width(ui_btnBack, 50);
    lv_obj_set_height(ui_btnBack, 50);
    lv_obj_set_x(ui_btnBack, -130);
    lv_obj_set_y(ui_btnBack, 90);
    lv_obj_set_align(ui_btnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBack, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBack, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnBack, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_btnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnBack, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnBack, ui_event_btnBack, LV_EVENT_ALL, NULL);

}
