// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"

void ui_Score_screen_init(void)
{
    ui_Score = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Score, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_flex_flow(ui_Score, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Score, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Score, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Score, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Score);
    lv_obj_set_width(ui_Label7, 40);
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -78);
    lv_obj_set_y(ui_Label7, -54);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Order");
    lv_obj_remove_flag(ui_Label7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Score);
    lv_obj_set_width(ui_Label13, 70);
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -78);
    lv_obj_set_y(ui_Label13, -54);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Module count");
    lv_obj_remove_flag(ui_Label13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Score);
    lv_obj_set_width(ui_Label9, 130);
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -78);
    lv_obj_set_y(ui_Label9, -54);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Completion time");
    lv_obj_remove_flag(ui_Label9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Score);
    lv_obj_set_width(ui_Label12, 56);
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -78);
    lv_obj_set_y(ui_Label12, -54);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Result");
    lv_obj_remove_flag(ui_Label12, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rlScoreOrder = lv_roller_create(ui_Score);
    lv_roller_set_options(ui_rlScoreOrder, "1\n2\n3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlScoreOrder, 40);
    lv_obj_set_height(ui_rlScoreOrder, 191);
    lv_obj_set_x(ui_rlScoreOrder, -37);
    lv_obj_set_y(ui_rlScoreOrder, -90);
    lv_obj_set_align(ui_rlScoreOrder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rlScoreOrder, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_rlScoreOrder, LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_border_color(ui_rlScoreOrder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreOrder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreOrder, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlScoreOrder, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreOrder, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreOrder, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_rlScoreModuleCount = lv_roller_create(ui_Score);
    lv_roller_set_options(ui_rlScoreModuleCount, "2\n3\n4", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlScoreModuleCount, 70);
    lv_obj_set_height(ui_rlScoreModuleCount, 191);
    lv_obj_set_x(ui_rlScoreModuleCount, -37);
    lv_obj_set_y(ui_rlScoreModuleCount, -90);
    lv_obj_set_align(ui_rlScoreModuleCount, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rlScoreModuleCount,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_border_color(ui_rlScoreModuleCount, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreModuleCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreModuleCount, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlScoreModuleCount, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreModuleCount, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreModuleCount, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_rlScoreCompletionTime = lv_roller_create(ui_Score);
    lv_roller_set_options(ui_rlScoreCompletionTime, "00m 00s 00ms\n00m 00s 00ms\n00m 00s 00ms", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlScoreCompletionTime, 130);
    lv_obj_set_height(ui_rlScoreCompletionTime, 191);
    lv_obj_set_x(ui_rlScoreCompletionTime, -37);
    lv_obj_set_y(ui_rlScoreCompletionTime, -90);
    lv_obj_set_align(ui_rlScoreCompletionTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rlScoreCompletionTime,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_border_color(ui_rlScoreCompletionTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreCompletionTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreCompletionTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlScoreCompletionTime, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreCompletionTime, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreCompletionTime, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_rlScoreResult = lv_roller_create(ui_Score);
    lv_roller_set_options(ui_rlScoreResult, "PASS\nFAIL\nPASS", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlScoreResult, 56);
    lv_obj_set_height(ui_rlScoreResult, 191);
    lv_obj_set_x(ui_rlScoreResult, -37);
    lv_obj_set_y(ui_rlScoreResult, -90);
    lv_obj_set_align(ui_rlScoreResult, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rlScoreResult,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_border_color(ui_rlScoreResult, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreResult, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlScoreResult, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreResult, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreResult, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_rlScoreOrder, ui_event_rlScoreOrder, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Score, ui_event_Score, LV_EVENT_ALL, NULL);

}
