// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"

lv_obj_t * ui_Score = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_rlScoreOrder = NULL;
lv_obj_t * ui_rlScoreModuleNum = NULL;
lv_obj_t * ui_rlScoreCompletionTime = NULL;
lv_obj_t * ui_rlScoreResult = NULL;
lv_obj_t * ui_Button3 = NULL;
// event funtions
void ui_event_Score(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Score_OnLoaded(e);
    }
}

void ui_event_rlScoreOrder(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Score_OnRollerOrderChange(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Score_OnClickBack(e);
    }
}

// build funtions

void ui_Score_screen_init(void)
{
    ui_Score = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Score, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_flex_flow(ui_Score, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Score, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Score, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Score, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Score, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Score, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Score);
    lv_obj_set_width(ui_Label7, 50);
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -78);
    lv_obj_set_y(ui_Label7, -54);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Order");
    lv_obj_remove_flag(ui_Label7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Score);
    lv_obj_set_width(ui_Label13, 65);
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -78);
    lv_obj_set_y(ui_Label13, -54);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Num of modules");
    lv_obj_remove_flag(ui_Label13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Score);
    lv_obj_set_width(ui_Label9, 130);
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -78);
    lv_obj_set_y(ui_Label9, -54);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Completion time");
    lv_obj_remove_flag(ui_Label9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Score);
    lv_obj_set_width(ui_Label12, 60);
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -78);
    lv_obj_set_y(ui_Label12, -54);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Result");
    lv_obj_remove_flag(ui_Label12, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rlScoreOrder = lv_roller_create(ui_Score);
    lv_roller_set_options(ui_rlScoreOrder, "1\n2\n3\n4\n5\n6", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlScoreOrder, 50);
    lv_obj_set_height(ui_rlScoreOrder, 155);
    lv_obj_set_x(ui_rlScoreOrder, -37);
    lv_obj_set_y(ui_rlScoreOrder, -90);
    lv_obj_set_align(ui_rlScoreOrder, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rlScoreOrder, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_rlScoreOrder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlScoreOrder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlScoreOrder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreOrder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreOrder, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlScoreOrder, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreOrder, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreOrder, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_rlScoreModuleNum = lv_roller_create(ui_Score);
    lv_roller_set_options(ui_rlScoreModuleNum, "2\n3\n4\n7\n9\n10", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlScoreModuleNum, 65);
    lv_obj_set_height(ui_rlScoreModuleNum, 155);
    lv_obj_set_x(ui_rlScoreModuleNum, -34);
    lv_obj_set_y(ui_rlScoreModuleNum, -108);
    lv_obj_set_align(ui_rlScoreModuleNum, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rlScoreModuleNum,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_rlScoreModuleNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlScoreModuleNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlScoreModuleNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreModuleNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreModuleNum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlScoreModuleNum, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreModuleNum, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreModuleNum, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_rlScoreCompletionTime = lv_roller_create(ui_Score);
    lv_roller_set_options(ui_rlScoreCompletionTime,
                          "00m 00s 00ms\n00m 00s 00ms\n00m 00s 00ms\n00m 00s 00ms\n00m 00s 00ms\n00m 00s 00ms", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlScoreCompletionTime, 130);
    lv_obj_set_height(ui_rlScoreCompletionTime, 155);
    lv_obj_set_x(ui_rlScoreCompletionTime, -37);
    lv_obj_set_y(ui_rlScoreCompletionTime, -90);
    lv_obj_set_align(ui_rlScoreCompletionTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rlScoreCompletionTime,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_rlScoreCompletionTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlScoreCompletionTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlScoreCompletionTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreCompletionTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreCompletionTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlScoreCompletionTime, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreCompletionTime, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreCompletionTime, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_rlScoreResult = lv_roller_create(ui_Score);
    lv_roller_set_options(ui_rlScoreResult, "PASS\nFAIL\nPASS\nPASS\nFAIL\nPASS", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlScoreResult, 60);
    lv_obj_set_height(ui_rlScoreResult, 155);
    lv_obj_set_x(ui_rlScoreResult, -37);
    lv_obj_set_y(ui_rlScoreResult, -90);
    lv_obj_set_align(ui_rlScoreResult, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rlScoreResult,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_rlScoreResult, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlScoreResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlScoreResult, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreResult, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlScoreResult, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlScoreResult, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlScoreResult, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_Score);
    lv_obj_set_width(ui_Button3, 45);
    lv_obj_set_height(ui_Button3, 45);
    lv_obj_set_x(ui_Button3, 134);
    lv_obj_set_y(ui_Button3, 94);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Button3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button3, &ui_img_arrow_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_width(ui_Button3, 1, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_add_event_cb(ui_rlScoreOrder, ui_event_rlScoreOrder, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Score, ui_event_Score, LV_EVENT_ALL, NULL);

}

void ui_Score_screen_destroy(void)
{
    if(ui_Score) lv_obj_del(ui_Score);

    // NULL screen variables
    ui_Score = NULL;
    ui_Label7 = NULL;
    ui_Label13 = NULL;
    ui_Label9 = NULL;
    ui_Label12 = NULL;
    ui_rlScoreOrder = NULL;
    ui_rlScoreModuleNum = NULL;
    ui_rlScoreCompletionTime = NULL;
    ui_rlScoreResult = NULL;
    ui_Button3 = NULL;

}
