// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_SCORE_H
#define UI_SCORE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Score
extern void ui_Score_screen_init(void);
extern void ui_Score_screen_destroy(void);
extern void ui_event_Score(lv_event_t * e);
extern lv_obj_t * ui_Score;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label12;
extern void ui_event_rlScoreOrder(lv_event_t * e);
extern lv_obj_t * ui_rlScoreOrder;
extern lv_obj_t * ui_rlScoreModuleNum;
extern lv_obj_t * ui_rlScoreCompletionTime;
extern lv_obj_t * ui_rlScoreResult;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

