// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"

lv_obj_t * ui_TimerSelect = NULL;
lv_obj_t * ui_rlSettingMinute = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_rlSettingSecond = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button16 = NULL;
// event funtions
void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Main_screen_init);
        TimerSelect_OnButtonNextClick(e);
    }
}

// build funtions

void ui_TimerSelect_screen_init(void)
{
    ui_TimerSelect = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TimerSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_TimerSelect, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_TimerSelect, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TimerSelect, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimerSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rlSettingMinute = lv_roller_create(ui_TimerSelect);
    lv_roller_set_options(ui_rlSettingMinute, "05\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55\n60", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_rlSettingMinute, 230);
    lv_obj_set_width(ui_rlSettingMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rlSettingMinute, -14);
    lv_obj_set_y(ui_rlSettingMinute, -27);
    lv_obj_set_align(ui_rlSettingMinute, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_rlSettingMinute, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlSettingMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rlSettingMinute, &ui_font_Digit_45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlSettingMinute, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlSettingMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlSettingMinute, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlSettingMinute, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlSettingMinute, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlSettingMinute, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_TimerSelect);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 132);
    lv_obj_set_y(ui_Label2, -24);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, ":");
    lv_obj_remove_flag(ui_Label2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rlSettingSecond = lv_roller_create(ui_TimerSelect);
    lv_roller_set_options(ui_rlSettingSecond, "00\n05\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55\n60",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_rlSettingSecond, 230);
    lv_obj_set_width(ui_rlSettingSecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rlSettingSecond, -14);
    lv_obj_set_y(ui_rlSettingSecond, -27);
    lv_obj_set_align(ui_rlSettingSecond, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_rlSettingSecond, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlSettingSecond, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rlSettingSecond, &ui_font_Digit_45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlSettingSecond, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlSettingSecond, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlSettingSecond, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlSettingSecond, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlSettingSecond, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlSettingSecond, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_TimerSelect);
    lv_obj_set_width(ui_Label11, 90);
    lv_obj_set_height(ui_Label11, 240);
    lv_obj_set_x(ui_Label11, 111);
    lv_obj_set_y(ui_Label11, 79);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "");
    lv_obj_remove_flag(ui_Label11, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_Label5 = lv_label_create(ui_TimerSelect);
    lv_obj_set_width(ui_Label5, 20);
    lv_obj_set_height(ui_Label5, 180);
    lv_obj_set_x(ui_Label5, 111);
    lv_obj_set_y(ui_Label5, 79);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "");
    lv_obj_remove_flag(ui_Label5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Button16 = lv_button_create(ui_TimerSelect);
    lv_obj_set_width(ui_Button16, 45);
    lv_obj_set_height(ui_Button16, 45);
    lv_obj_set_x(ui_Button16, 140);
    lv_obj_set_y(ui_Button16, 42);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button16, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Button16, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button16, &ui_img_arrow_right_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button16, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_width(ui_Button16, 1, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);

}

void ui_TimerSelect_screen_destroy(void)
{
    if(ui_TimerSelect) lv_obj_del(ui_TimerSelect);

    // NULL screen variables
    ui_TimerSelect = NULL;
    ui_rlSettingMinute = NULL;
    ui_Label2 = NULL;
    ui_rlSettingSecond = NULL;
    ui_Label11 = NULL;
    ui_Label5 = NULL;
    ui_Button16 = NULL;

}
