// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_TIMERSELECT_H
#define UI_TIMERSELECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TimerSelect
extern void ui_TimerSelect_screen_init(void);
extern void ui_TimerSelect_screen_destroy(void);
extern lv_obj_t * ui_TimerSelect;
extern lv_obj_t * ui_rlSettingMinute;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_rlSettingSecond;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

