// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#include "ui.h"

lv_obj_t * ui_TimerSetting = NULL;
lv_obj_t * ui_rlSettingMinute = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_rlSettingSecond = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_btnTimerSettingSave = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_TimerSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_state_modify(ui_btnTimerSettingSave, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_rlSettingMinute(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_btnTimerSettingSave, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_rlSettingSecond(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_btnTimerSettingSave, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_btnTimerSettingSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnTimerSettingSave, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        TimerSetting_OnButtonSaveClick(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_TimerSetting_screen_init(void)
{
    ui_TimerSetting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TimerSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_TimerSetting, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_TimerSetting, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TimerSetting, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimerSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rlSettingMinute = lv_roller_create(ui_TimerSetting);
    lv_roller_set_options(ui_rlSettingMinute, "05\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55\n60", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_rlSettingMinute, 230);
    lv_obj_set_width(ui_rlSettingMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rlSettingMinute, -14);
    lv_obj_set_y(ui_rlSettingMinute, -27);
    lv_obj_set_align(ui_rlSettingMinute, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_rlSettingMinute, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlSettingMinute, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlSettingMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlSettingMinute, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlSettingMinute, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlSettingMinute, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlSettingMinute, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_TimerSetting);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 132);
    lv_obj_set_y(ui_Label2, -24);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, ":");
    lv_obj_remove_flag(ui_Label2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rlSettingSecond = lv_roller_create(ui_TimerSetting);
    lv_roller_set_options(ui_rlSettingSecond,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_rlSettingSecond, 230);
    lv_obj_set_width(ui_rlSettingSecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rlSettingSecond, -14);
    lv_obj_set_y(ui_rlSettingSecond, -27);
    lv_obj_set_align(ui_rlSettingSecond, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_rlSettingSecond, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlSettingSecond, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlSettingSecond, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlSettingSecond, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rlSettingSecond, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlSettingSecond, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rlSettingSecond, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_TimerSetting);
    lv_obj_set_width(ui_Label11, 30);
    lv_obj_set_height(ui_Label11, 240);
    lv_obj_set_x(ui_Label11, 111);
    lv_obj_set_y(ui_Label11, 79);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "");
    lv_obj_remove_flag(ui_Label11, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_Label5 = lv_label_create(ui_TimerSetting);
    lv_obj_set_width(ui_Label5, 50);
    lv_obj_set_height(ui_Label5, 110);
    lv_obj_set_x(ui_Label5, 111);
    lv_obj_set_y(ui_Label5, 79);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "");
    lv_obj_remove_flag(ui_Label5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_btnTimerSettingSave = lv_button_create(ui_TimerSetting);
    lv_obj_set_width(ui_btnTimerSettingSave, 100);
    lv_obj_set_height(ui_btnTimerSettingSave, 50);
    lv_obj_set_x(ui_btnTimerSettingSave, 139);
    lv_obj_set_y(ui_btnTimerSettingSave, 42);
    lv_obj_set_align(ui_btnTimerSettingSave, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnTimerSettingSave, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_btnTimerSettingSave, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTimerSettingSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTimerSettingSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnTimerSettingSave, lv_color_hex(0x35C61F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTimerSettingSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnTimerSettingSave, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnTimerSettingSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnTimerSettingSave, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnTimerSettingSave, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_btnTimerSettingSave, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_width(ui_btnTimerSettingSave, 1, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Label10 = lv_label_create(ui_btnTimerSettingSave);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 110);
    lv_obj_set_y(ui_Label10, -69);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Save");
    lv_obj_remove_flag(ui_Label10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_button_create(ui_TimerSetting);
    lv_obj_set_width(ui_Button16, 100);
    lv_obj_set_height(ui_Button16, 50);
    lv_obj_set_x(ui_Button16, 139);
    lv_obj_set_y(ui_Button16, 42);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button16, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Button16, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button16, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_width(ui_Button16, 1, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Label1 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 110);
    lv_obj_set_y(ui_Label1, -69);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Close");
    lv_obj_remove_flag(ui_Label1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_rlSettingMinute, ui_event_rlSettingMinute, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rlSettingSecond, ui_event_rlSettingSecond, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTimerSettingSave, ui_event_btnTimerSettingSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimerSetting, ui_event_TimerSetting, LV_EVENT_ALL, NULL);

}

void ui_TimerSetting_screen_destroy(void)
{
    if(ui_TimerSetting) lv_obj_del(ui_TimerSetting);

    // NULL screen variables
    ui_TimerSetting = NULL;
    ui_rlSettingMinute = NULL;
    ui_Label2 = NULL;
    ui_rlSettingSecond = NULL;
    ui_Label11 = NULL;
    ui_Label5 = NULL;
    ui_btnTimerSettingSave = NULL;
    ui_Label10 = NULL;
    ui_Button16 = NULL;
    ui_Label1 = NULL;

}
