// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Host_Timer_Project

#ifndef UI_TIMERSETTING_H
#define UI_TIMERSETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TimerSetting
extern void ui_TimerSetting_screen_init(void);
extern void ui_TimerSetting_screen_destroy(void);
extern void ui_event_TimerSetting(lv_event_t * e);
extern lv_obj_t * ui_TimerSetting;
extern void ui_event_rlSettingMinute(lv_event_t * e);
extern lv_obj_t * ui_rlSettingMinute;
extern lv_obj_t * ui_Label2;
extern void ui_event_rlSettingSecond(lv_event_t * e);
extern lv_obj_t * ui_rlSettingSecond;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label5;
extern void ui_event_btnTimerSettingSave(lv_event_t * e);
extern lv_obj_t * ui_btnTimerSettingSave;
extern lv_obj_t * ui_Label10;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

