name: CI/CD C++ Visual Studio - Branch build

on:
  workflow_dispatch: # Manual trigger
    inputs:
      branch_name:
        description: 'Branch name'
        required: true
        default: 'feature_Host_Timer' # Default branch

env:
  SOLUTION_FILE: Simulator/LVGL.sln
  BUILD_CONFIG: Debug
  PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository from specified branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }} # Use branch name

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages (if applicable)
        run: nuget restore ${{ env.SOLUTION_FILE }}

      - name: Build solution
        run: msbuild ${{ env.SOLUTION_FILE }} /p:Configuration=${{ env.BUILD_CONFIG }} /p:Platform=${{ env.PLATFORM }} /m /verbosity:minimal

      - name: Upload build artifacts (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_CONFIG }}-${{ env.PLATFORM }}-${{ github.event.inputs.branch_name }} # Thêm tên branch vào tên artifact
          path: Simulator/Output/Binaries/${{ env.BUILD_CONFIG }}/${{ env.PLATFORM }}/**
